### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by BenzoIsHere** [UnamSanctam/UnamBinder#1]
Good one my friend, would this work in the same manner as the downloader? I raise a concern for the actual detections, shall I bind the downloader to another file? Would this raise the detection? Also, is there any way to get a contact of yours to discuss some business matters? 🗡️

**Comment by UnamSanctam** [comment]
Yes this works the same way as the downloader but it embeds all the files into the final executable instead, it should theoretically probably have more detections than the downloader but since it's a native file it remains to be seen how well antiviruses detects it in the future when more people use it. Every file in encrypted/obfuscated so it shouldn't really matter which file you embed into it.

I have a Discord: Unam Sanctam#3135.

**Comment by BenzoIsHere** [comment]
All right, sent you a friend request just now.
