### ISSUE TITLE
Dosent bypass windows protector

### ISSUE THREAD

**Issue by ZribeDev** [UnamSanctam/UnamBinder#11]
same as the title says it dosent bypass windows protector

**Comment by ZribeDev** [comment]
when i send it to my windows machine it just dosent work and windows defender instantly removed it.
i built it probably 2 times cause i forgot something.

**Comment by UnamSanctam** [comment]
Yes, the project is public and open source so it will be detected (just like any other project on GitHub), you'll need a good crypter (with "Shellcode Loader" enabled) or obfuscator (with "Shellcode Loader" disabled) to make it undetected. What "Bypass Windows Defender" does is that it adds exclusions when you run the miner so that it won't get detected in the future on that computer even if your build gets detected.

**Comment by ZribeDev** [comment]
Oh Okay! Btw great project!
